compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

logFilters:
    - code: YN0076
      level: discard

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
