compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0076
    level: discard

nmMode: hardlinks-global

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
