import type { IObjectOf, Nullable } from "@thi.ng/api";

// prettier-ignore
export const GLOSSARY: IObjectOf<Nullable<string>[]> = {
	alpha: ["Alpha channel"],
	allpass: ["Filter type",,"All-pass_filter"],
	ansi: ["ANSI escape codes",, "ANSI_escape_code"],
	aos: ["Array of Structures", "array-of-structures"],
	ast: ["Abstract syntax tree",, "Abstract_syntax_tree"],
	avif: ["AV1 Image File Format",, "AVIF"],
	axidraw: ["Pen plotter"],
	bencode: ["Data serialization format",,"Bencode"],
	biquad: ["Filter type",, "Digital_biquad_filter"],
	bitfield: ["Data structure",, "Bit_field"],
	c: ["Programming language",, "C_(programming_language)"],
	cli: ["Command-line interface",, "Command-line_interface"],
	codegen: ["Code generation", "code-generation"],
	csp: ["Communicating Sequential Processes",, "Communicating_sequential_processes"],
	csv: ["File format",, "Comma-separated_values"],
	dag: ["Directed Acyclic Graph", "directed-acyclic-graph"],
	dce: ["Dead-code elimination",, "Dead-code_elimination"],
	"disjoint-set": ["Data structure",, "Disjoint-set_data_structure"],
	dsl: ["Domain-specific language",,"Domain-specific_language"],
	dsp: ["Digital Signal Processing",, "Digital_signal_processing"],
	ecs: ["Entity Component System", "entity-component-system"],
	fft: ["Fast Fourier Transform",, "Fast_Fourier_transform"],
	forth: ["Programming language",, "Forth_(programming_language)"],
	"free-list": ["Data structure",,"Free_list"],
	fsm: ["Finite State Machine",, "Finite-state_machine"],
	gpgpu: ["General Purpose GPU processing",, "General-purpose_computing_on_graphics_processing_units"],
	"higher-order": ["Functional programming",, "Higher-order_function"],
	hilbert: ["Space-filling curve",, "Hilbert_curve"],
	hdpi: ["High-density display support"],
	morton: ["Space-filling curve",, "Z-order_curve"],
	io: ["Input/Output"],
	ioc: ["Inversion of control",, "Inversion_of_control"],
	levenshtein: ["Edit distance",, "Levenshtein_distance"],
	"no-browser": ["not aimed at web browser usage"],
	obj: ["Geometry file format",, "Wavefront_.obj_file"],
	pbm: ["Image file format",, "Netpbm"],
	set: ["Data structure",, "Set_(abstract_data_type)"],
	simd: ["Single Instruction, Multiple Data", "simd"],
	soa: ["Structure of Arrays", "structure-of-arrays"],
	"sutherland-hodgeman": ["Polygon clipping algorithm",, "Sutherland–Hodgman_algorithm"],
	tiff: ["Image file format",, "TIFF"],
	ttl: ["Time-to-live",, "Time_to_live"],
	wav: ["Audio file format",, "WAV"],
	"z-curve": ["Space-filling curve",, "Z-order_curve"],
	zig: ["Programming language",, "Zig_(programming_language)"],
};
