//! Generated by @thi.ng/wasm-api at 2022-11-15T05:32:32.343Z - DO NOT EDIT!

const std = @import("std");
const wasm = @import("wasmapi");

pub const ScheduleType = enum(i32) {
    /// One-off execution in the future
    once,
    /// Recurring execution at fixed interval
    interval,
    /// As soon as possible execution
    immediate,
};
