//! Generated by @thi.ng/wasm-api at 2022-11-06T12:59:55.593Z - DO NOT EDIT!

const std = @import("std");

pub const ScheduleType = enum(i32) {
    /// One-off execution in the future
    once,
    /// Recurring execution at fixed interval
    interval,
    /// As soon as possible execution
    immediate,
};
