//! Generated by @thi.ng/wasm-api-bindgen at 2025-09-01T11:06:15.300Z
//! DO NOT EDIT!

const std = @import("std");
const bindgen = @import("wasm-api-bindgen");

pub const ScheduleType = enum(i32) {
    /// One-off execution in the future
    once,
    /// Recurring execution at fixed interval
    interval,
    /// As soon as possible execution
    immediate,
    /// Same as `requestAnimationFrame()` (or equivalent if not available in JS env)
    raf,
};
