//! Generated by @thi.ng/wasm-api at 2022-10-30T21:19:20.651Z - DO NOT EDIT!

const std = @import("std");

pub const TimerType = enum(i32) {
    /// One-off execution in the future
    once,
    /// Recurring execution at fixed interval
    interval,
    /// As soon as possible execution
    immediate,
};
