// DO NOT EDIT THIS FILE!
//
// Stubs for auto-generated parser module (using pegjs 0.10.+)
// To rebuild the parser run either: `yarn build` or `yarn peg`
export function SyntaxError(message: string, expected: string, found: any, loc: any) {
    message; expected; found; loc;
}

export function parse(input: string, options?: any): any {
    input; options;
    return null;
}
