#!/bin/sh
BUILD=build

if [ $# = 1 ]; then
    examples="examples/$1"
else
    examples="examples/*"
fi

for e in $examples; do
    if [ -d "$e" ] && [ ! -e "$e/.skip" ]; then
        ebuild="$e/$BUILD"
        echo "------------------------------"
        echo "building $e..."
        echo "------------------------------"
        rm -rf "$ebuild" "$e/.cache"
        if [ ! -r "$e"/package.json ]; then
            continue
        fi
        if grep --quiet '"skip": true' "$e"/package.json; then
            continue
        fi
        if grep --quiet build:webpack "$e"/package.json; then
            (cd "$e" && yarn build:webpack)
            cp "$e/index.html" "$ebuild"/index.html
            js=$(basename $(ls "$ebuild"/bundle*.js))
            sed -i '' -E 's,<script type="text/javascript" src="\./src/index.ts",<script type="text/javascript" src="'"$js"'",' "$ebuild"/index.html
        else
            (cd "$e" && yarn build)
        fi
        if [ 0 -eq $? ]; then
            rm -rf "$ebuild"/_snowpack "$ebuild"/_dist_ "$ebuild"/web_modules
            src=$(find "$ebuild" -name '*.js')
            for js in $src; do
                node_modules/.bin/terser -c -m --ecma 6 -o "$js" "$js"
                sed -i '' -E 's/Object\.defineProperty([a-z]\+,"__esModule",{value:\!0});//g' "$js"
                sed -i '' -E 's/Object\.defineProperty([a-z]\+,"__esModule",{value:\!0}),\([^f]\)/(\1)/g' "$js"
                # gzip -c "$js" > "$js".gz
                ls -la "$js"
            done
            # sed -i 's/src="\//src=".\//g' $e/out/index.html
        else
            echo "skipping..."
        fi
    fi
done
