#!/usr/bin/env node
const fs = require("fs");

/**
 * Recursively reads given directory and returns file names matching
 * given extension.
 *
 * @param {*} dir
 * @param {*} ext
 */
function* files(dir, ext) {
    for (let f of fs.readdirSync(dir)) {
        const curr = dir + "/" + f;
        if (f.endsWith(ext)) {
            yield curr;
        } else if (fs.statSync(curr).isDirectory()) {
            yield* files(curr, ext);
        }
    }
}

for (let f of files("packages", ".map")) {
    if (f.indexOf("/lib/") === -1) {
        console.log(f);
        fs.unlinkSync(f);
    }
}
