#!/usr/bin/env bash

readonly MODULE="packages/$1"
readonly AUTHOR="Karsten Schmidt"
readonly EMAIL="k+npm@thi.ng"

IFS='-' read -r -a parts <<< "$1"

for i in "${parts[@]}"; do
    INITIAL="$INITIAL${i:0:1}"
done

echo "generating module: $MODULE ($INITIAL)"
mkdir -p "$MODULE"

echo "creating /src /test /bench /dev /export /tools"
mkdir -p "$MODULE"/src "$MODULE"/test "$MODULE"/bench "$MODULE"/dev "$MODULE"/export "$MODULE"/tools

echo "creating index.ts stubs..."
touch "$MODULE"/src/index.ts "$MODULE"/tools/index.ts

cp packages/api/LICENSE "$MODULE"/

echo "writing test skeleton..."
cat << EOF > "$MODULE"/test/index.ts
import { group } from "@thi.ng/testament";
// import * as assert from "assert";
// import { } from "../src";

group("$1", {

});
EOF

echo "writing bench skeleton..."
cat << EOF > "$MODULE"/bench/index.ts
import { suite } from "@thi.ng/bench";
// import { } from "../src";

suite([
	{ title: "", fn: () => {}, opts: {} },
], {
	iter: 1000,
	warmup: 100,
	size: 1,
});
EOF

echo "writing package.json..."
cat << EOF > "$MODULE"/package.json
{
	"name": "@thi.ng/$1",
	"version": "0.0.1",
	"description": "TODO",
	"type": "module",
	"module": "./index.js",
	"typings": "./index.d.ts",
	"sideEffects": false,
	"repository": {
		"type": "git",
		"url": "https://github.com/thi-ng/umbrella.git"
	},
	"homepage": "https://github.com/thi-ng/umbrella/tree/master/packages/$1#readme",
	"funding": [
		{
			"type": "github",
			"url": "https://github.com/sponsors/postspectacular"
		},
		{
			"type": "patreon",
			"url": "https://patreon.com/thing_umbrella"
		}
	],
	"author": "$AUTHOR <$EMAIL>",
	"license": "Apache-2.0",
	"scripts": {
		"build": "yarn clean && tsc --declaration",
		"clean": "rimraf '*.js' '*.d.ts' '*.map' doc",
		"doc": "typedoc --excludePrivate --excludeInternal --out doc src/index.ts",
		"doc:ae": "mkdir -p .ae/doc .ae/temp && api-extractor run --local --verbose",
		"doc:readme": "yarn doc:stats && tools:readme",
		"doc:stats": "tools:module-stats",
		"pub": "yarn npm publish --access public",
		"test": "testament test"
	},
	"dependencies": {
		"@thi.ng/api": "^8.4.4"
	},
	"devDependencies": {
		"@microsoft/api-extractor": "^7.33.5",
		"@thi.ng/testament": "^0.3.4",
		"rimraf": "^3.0.2",
		"tools": "workspace:^",
		"typedoc": "^0.23.18",
		"typescript": "^4.8.4"
	},
	"keywords": [
		"typescript"
	],
	"publishConfig": {
		"access": "public"
	},
	"browser": {
		"process": false,
		"setTimeout": false
	},
	"files": [
		"*.js",
		"*.d.ts"
	],
	"exports": {
		".": {
			"default": "./index.js"
		}
	},
	"thi.ng": {
		"status": "alpha",
		"year": 2022
	}
}
EOF

echo "writing module tsconfig.json..."
cat << EOF > "$MODULE"/tsconfig.json
{
	"extends": "../../tsconfig.json",
	"compilerOptions": {
		"outDir": "."
	},
	"include": [
		"./src/**/*.ts"
	]
}
EOF

echo "writing api-extractor.json..."
cat << EOF > "$MODULE"/api-extractor.json
{
	"extends": "../../api-extractor.json"
}
EOF

echo "writing tpl.readme.md..."
cat << 'EOF' > "$MODULE"/tpl.readme.md
# ${pkg.banner}

[![npm version](https://img.shields.io/npm/v/${pkg.name}.svg)](https://www.npmjs.com/package/${pkg.name})
![npm downloads](https://img.shields.io/npm/dm/${pkg.name}.svg)
[![Twitter Follow](https://img.shields.io/twitter/follow/thing_umbrella.svg?style=flat-square&label=twitter)](https://twitter.com/thing_umbrella)

This project is part of the
[@thi.ng/umbrella](https://github.com/thi-ng/umbrella/) monorepo.

<!-- TOC -->

## About

${pkg.description}

${status}

${supportPackages}

${relatedPackages}

${blogPosts}

## Installation

${pkg.install}

${pkg.size}

## Dependencies

${pkg.deps}

${examples}

## API

${docLink}

TODO

## Authors

${authors}

${pkg.cite}

## License

&copy; ${copyright} // ${license}
EOF

echo "refreshing monorepo index..."
yarn install &>/dev/null
echo "DONE"
