#!/bin/sh

readonly MODULE="packages/$1"
readonly AUTHOR="Karsten Schmidt"
readonly EMAIL="k+npm@thi.ng"

IFS='-' read -r -a parts <<< "$1"

for i in "${parts[@]}"; do
    INITIAL="$INITIAL${i:0:1}"
done

echo "generating module: $MODULE ($INITIAL)"
mkdir -p $MODULE

echo "creating /src & /test folders..."
mkdir -p $MODULE/src $MODULE/test
touch $MODULE/src/index.ts

cp packages/api/LICENSE $MODULE/

echo "writing test skeleton..."
cat << EOF > $MODULE/test/index.ts
// import * as assert from "assert";
// import * as $INITIAL from "../src/index";

describe("$1", () => {
    it("tests pending");
});
EOF

echo "writing package.json..."
cat << EOF > $MODULE/package.json
{
    "name": "@thi.ng/$1",
    "version": "0.0.1",
    "description": "TODO",
    "main": "./index.js",
    "typings": "./index.d.ts",
    "repository": {
        "type": "git",
        "url": "https://github.com/thi-ng/umbrella.git"
    },
    "homepage": "https://github.com/thi-ng/umbrella/tree/master/packages/$1",
    "author": "$AUTHOR <$EMAIL>",
    "license": "Apache-2.0",
    "scripts": {
        "build": "yarn run clean && tsc --declaration",
        "clean": "rm -rf *.js *.d.ts .nyc_output build coverage doc",
        "cover": "yarn test && nyc report --reporter=lcov",
        "doc": "node_modules/.bin/typedoc --mode modules --out doc src",
        "pub": "yarn run build && yarn publish --access public",
        "test": "rm -rf build && tsc -p test && nyc mocha build/test/*.js"
    },
    "devDependencies": {
        "@types/mocha": "^5.2.5",
        "@types/node": "^10.12.0",
        "mocha": "^5.2.0",
        "nyc": "^13.1.0",
        "typedoc": "^0.13.0",
        "typescript": "^3.1.3"
    },
    "dependencies": {
        "@thi.ng/api": "^4.2.2"
    },
    "keywords": [
        "ES6",
        "typescript"
    ],
    "publishConfig": {
        "access": "public"
    }
}
EOF

echo "writing module tsconfig.json..."
cat << EOF > $MODULE/tsconfig.json
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "."
    },
    "include": [
        "./src/**/*.ts"
    ]
}
EOF

echo "writing test tsconfig.json..."
cat << EOF > $MODULE/test/tsconfig.json
{
    "extends": "../../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../build"
    },
    "include": [
        "./**/*.ts",
        "../src/**/*.ts"
    ]
}
EOF

echo "writing .npmignore..."
cat << EOF > $MODULE/.npmignore
build
coverage
dev
doc
export
src*
test
.nyc_output
tsconfig.json
*.tgz
*.html
EOF

echo "writing README.md..."
cat << EOF > $MODULE/README.md
# @thi.ng/$1

[![npm (scoped)](https://img.shields.io/npm/v/@thi.ng/$1.svg)](https://www.npmjs.com/package/@thi.ng/$1)
![npm downloads](https://img.shields.io/npm/dm/@thi.ng/$1.svg)
[![Twitter Follow](https://img.shields.io/twitter/follow/thing_umbrella.svg?style=flat-square&label=twitter)](https://twitter.com/thing_umbrella)

This project is part of the
[@thi.ng/umbrella](https://github.com/thi-ng/umbrella/) monorepo.

<!-- TOC depthFrom:2 depthTo:3 -->

<!-- /TOC -->

## About

TODO...

## Installation

\`\`\`bash
yarn add @thi.ng/$1
\`\`\`

## Dependencies

- TODO...

## Usage examples

\`\`\`ts
import * as $INITIAL from "@thi.ng/$1";
\`\`\`

## Authors

- $AUTHOR

## License

&copy; 2018 $AUTHOR // Apache Software License 2.0
EOF
