#!/bin/sh

readonly MODULE="examples/$1"
readonly AUTHOR="Karsten Schmidt"
readonly EMAIL="k+npm@thi.ng"

echo "generating module: $MODULE"
mkdir -p $MODULE

echo "creating /src folder..."
mkdir -p $MODULE/src
cat << EOF > $MODULE/src/index.ts
import { } from "@thi.ng/hdom";

if (process.env.NODE_ENV !== "production") {
    const hot = (<any>module).hot;
    hot && hot.dispose(() => {});
}
EOF

echo "writing package.json..."
cat << EOF > $MODULE/package.json
{
    "name": "$1",
    "version": "0.0.1",
    "repository": "https://github.com/thi-ng/umbrella",
    "author": "$AUTHOR <$EMAIL>",
    "license": "Apache-2.0",
    "scripts": {
        "clean": "rm -rf .cache build out",
        "build": "yarn clean && parcel build index.html -d out --public-url ./ --no-source-maps --no-cache --detailed-report",
        "start": "parcel index.html -p 8080 --open"
    },
    "devDependencies": {
        "parcel-bundler": "^1.10.3",
        "terser": "^3.11.0",
        "typescript": "^3.2.2"
    },
    "dependencies": {
        "@thi.ng/api": "latest",
        "@thi.ng/atom": "latest",
        "@thi.ng/rstream": "latest",
        "@thi.ng/transducers-hdom": "latest"
    },
    "browserslist": [
        "last 3 Chrome versions"
    ],
    "browser": {
        "process": false
    }
}
EOF

echo "writing tsconfig.json..."
cat << EOF > $MODULE/tsconfig.json
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": ".",
        "target": "es6",
        "sourceMap": true
    },
    "include": [
        "./src/**/*.ts"
    ]
}
EOF

echo "writing .gitignore..."
cat << EOF > $MODULE/.gitignore
.cache
out
node_modules
yarn.lock
*.js
EOF

echo "writing index.html..."
cat << EOF > $MODULE/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>$1</title>
    <link href="https://unpkg.com/tachyons@4/css/tachyons.min.css" rel="stylesheet">
    <style>
    </style>
</head>
<body>
    <div id="app"></div>
    <script type="text/javascript" src="./src/index.ts"></script>
</body>
</html>
EOF

echo "writing README.md..."
cat << EOF > $MODULE/README.md
# $1

[Live demo](http://demo.thi.ng/umbrella/$1/)

\`\`\`bash
git clone https://github.com/thi-ng/umbrella.git
cd umbrella/examples/$1
yarn install
yarn start
\`\`\`

## Authors

- $AUTHOR

## License

&copy; 2018 $AUTHOR // Apache Software License 2.0
EOF
