#!/bin/sh

readonly target="s3://demo.thi.ng/umbrella"
readonly opts="--profile toxi-s3 --acl public-read"

if [ $# == 1 ]; then
    modules="examples/$1"
else
    modules="examples/*"
fi

for m in $modules; do
    if [ -d "$m" ] && [ ! -e "$m/.skip" ]; then
        name=$(echo $m | cut -d '/' -f 2)
        dest="$target/$name"
        src=$(ls $m/out/*.js.gz | cut -d '/' -f 4)
        len=${#src}
        src="${src:0:len-3}"
        echo "------------------------------"
        echo "uploading $m ($src)..."
        echo "------------------------------"
        assets=$(find $m/out/ -name '*.png')
        if [ ! -z $assets ]; then
            aws s3 cp $m/out/*.png $dest/ $opts
        fi
        assets=$(find $m/out/ -name '*.json')
        if [ ! -z $assets ]; then
            for a in $assets; do
                origname=$(basename -- "$a")
                gzip $a
                aws s3 cp $a.gz $dest/$origname $opts --content-type "application/json; charset=utf-8" --content-encoding gzip
            done
        fi
        aws s3 cp $m/out/*.js.gz $dest/$src $opts --content-type "application/javascript; charset=utf-8" --content-encoding gzip
        aws s3 cp $m/out/index.html $dest/ $opts --cache-control "max-age=900"
    fi
done
