//! Generated by @thi.ng/wasm-api at 2022-10-02T18:59:48.751Z - DO NOT EDIT!

pub const EventType = enum(i32) {
    UNKOWN = -1,
    MOUSE,
    TOUCH,
    WHEEL,
    INPUT,
    KEY,
    FOCUS,
    BLUR,
    RESIZE,
};

pub const KeyModifier = enum(u8) {
    SHIFT = 1,
    CTRL = 2,
    ALT = 4,
    META = 8,
};

pub const WindowInfo = struct {
    innerWidth: u16,
    innerHeight: u16,
    dpr: u8,
};

pub const Event = struct {
    target: i32,
    clientX: u32 = 0,
    clientY: u32 = 0,
    type: EventType,
    buttons: u8 = 0,
    modifiers: u8 = 0,
    key: [8]u8,
};

pub const CreateElementOpts = struct {
    /// DOM element name
    tag: []const u8,
    /// Parent element ID. If >=0 the new element will be attached to that parent
    /// element. Set to -1 to leave new element unattached
    parent: i32,
    /// Insertion index for new element or -1 to append (default)
    index: i32 = -1,
};

pub const CreateCanvasOpts = struct {
    width: u16,
    height: u16,
    /// Same as CreateElementOpts.parent
    parent: i32,
    /// Same as CreateElementOpts.index
    index: i32 = -1,
    dpr: u8 = 1,
};
